package models

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"gorm.io/gorm"
	"gorm.io/gorm/schema"
)

// UUID keeps IDs as native uuid columns on PostgreSQL and CHAR(36) on MySQL.
// Values are generated by the database package's create callback so both
// databases use the same application-side UUID generation path.
type UUID string

func NewUUID() UUID {
	return UUID(uuid.NewString())
}

func (UUID) GormDataType() string {
	return "uuid"
}

func (UUID) GormDBDataType(db *gorm.DB, _ *schema.Field) string {
	if db.Dialector.Name() == "postgres" {
		return "uuid"
	}
	return "char(36)"
}

func (u *UUID) Scan(value any) error {
	switch value := value.(type) {
	case nil:
		*u = ""
	case string:
		*u = UUID(value)
	case []byte:
		*u = UUID(string(value))
	default:
		return fmt.Errorf("scan UUID from %T", value)
	}
	return nil
}

func (u UUID) Value() (driver.Value, error) {
	if u == "" {
		return nil, nil
	}
	return string(u), nil
}

func (u UUID) String() string {
	return string(u)
}
